spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
    lettuce:
      pool:
        max-active: 16
        max-idle: 16
        min-idle: 0
logging:
  file:
    name:
    path:
