server:
  port: 8767

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: livealive
    hikari:
      maximum-pool-size: 8

  kafka:
    bootstrap-servers:
    - 172.19.3.194:9092
    - 172.19.3.195:9092
    - 172.19.3.196:9092
    consumer:
      group-id: building-test
      #关闭自动提交
      enable-auto-commit: false
#      max-poll-records: 128
      fetch-min-size: 128
      fetch-max-wait: 30
      client-id: dwx-pc
    listener:
      # 配置手动提交方式
      ack-mode: manual
      # 并发度
      concurrency: 6