server:
  port: 8767
  
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/credit?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: ENC(NeBgRZqjo+E5wQkYt+FopfD1/jqOBoc0)
  #    password: livealive

  #redis config
  redis:
    database: 7
    host: localhost
    port: 6379
    timeout: 5000
    #boot1.5.X配置有所不同，lettuce,连接池必须依赖commons-pool2 jar
    jedis:
      pool:
        max-active: 10
        min-idle: 0
        max-wait: -1
        max-idle: 10
        
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    publisher-confirms: true
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: AUTO
  kafka:
    bootstrap-servers:
#    - localhost:9092
    - 172.19.3.194:9092
    - 172.19.3.195:9092
    - 172.19.3.196:9092
    consumer:
      group-id: test

jasypt:
  encryptor:
    password: 123456
    algorithm: PBEWithMD5AndDES
    #3.0.0以后的新版本兼容老版本
    iv-generator-classname: org.jasypt.iv.NoIvGenerator