/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dwx' at '16-9-18 下午3:17' with Gradle 2.13
 *
 * @author dwx, @date 16-9-18 下午3:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
